/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/study-table.glb --keepnames --types -o tmp/Study.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    group1496394384: THREE.Mesh
    group68997284: THREE.Mesh
    group2071438645: THREE.Mesh
    group713691426: THREE.Mesh
    group972927717: THREE.Mesh
    group669999047: THREE.Mesh
    group619448590: THREE.Mesh
    group1707961635: THREE.Mesh
    group805448854: THREE.Mesh
    group557231250: THREE.Mesh
    group555283123: THREE.Mesh
    group640447708: THREE.Mesh
    group93528968: THREE.Mesh
    group26582017: THREE.Mesh
    group1582685801: THREE.Mesh
    group233785688: THREE.Mesh
    group535361081: THREE.Mesh
    group207786523: THREE.Mesh
    group528447376: THREE.Mesh
    group1516688743: THREE.Mesh
    group1172600554: THREE.Mesh
    group1931015399: THREE.Mesh
    group938183579: THREE.Mesh
    group1349309159: THREE.Mesh
    group1674386045: THREE.Mesh
    group1357428381: THREE.Mesh
    group860642019: THREE.Mesh
    group95791140: THREE.Mesh
    group1081262426: THREE.Mesh
    group1287934658: THREE.Mesh
    group1218717193: THREE.Mesh
    group1980010167: THREE.Mesh
    group4898611: THREE.Mesh
    group1164661945: THREE.Mesh
    group410240839: THREE.Mesh
    group446381025: THREE.Mesh
    group242060174: THREE.Mesh
    group1142374827: THREE.Mesh
    group871706007: THREE.Mesh
    group1093773099: THREE.Mesh
    group1805364148: THREE.Mesh
    group1607230787: THREE.Mesh
    group977220737: THREE.Mesh
    group1478190301: THREE.Mesh
    group1927025453: THREE.Mesh
    group2101546053: THREE.Mesh
    group893657134: THREE.Mesh
    group59110847: THREE.Mesh
  }
  materials: {
    mat23: THREE.MeshStandardMaterial
    mat20: THREE.MeshStandardMaterial
    mat22: THREE.MeshStandardMaterial
    mat24: THREE.MeshStandardMaterial
    mat16: THREE.MeshStandardMaterial
    mat21: THREE.MeshStandardMaterial
    mat19: THREE.MeshStandardMaterial
    mat18: THREE.MeshStandardMaterial
    mat11: THREE.MeshStandardMaterial
    mat15: THREE.MeshStandardMaterial
    mat8: THREE.MeshStandardMaterial
    mat25: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/study-table.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="group1496394384" geometry={nodes.group1496394384.geometry} material={materials.mat23} />
      <mesh name="group68997284" geometry={nodes.group68997284.geometry} material={materials.mat23} />
      <mesh name="group2071438645" geometry={nodes.group2071438645.geometry} material={materials.mat23} />
      <mesh name="group713691426" geometry={nodes.group713691426.geometry} material={materials.mat23} />
      <mesh name="group972927717" geometry={nodes.group972927717.geometry} material={materials.mat23} />
      <mesh name="group669999047" geometry={nodes.group669999047.geometry} material={materials.mat23} />
      <mesh name="group619448590" geometry={nodes.group619448590.geometry} material={materials.mat23} />
      <mesh name="group1707961635" geometry={nodes.group1707961635.geometry} material={materials.mat23} />
      <mesh name="group805448854" geometry={nodes.group805448854.geometry} material={materials.mat23} />
      <mesh name="group557231250" geometry={nodes.group557231250.geometry} material={materials.mat23} />
      <mesh name="group555283123" geometry={nodes.group555283123.geometry} material={materials.mat23} />
      <mesh name="group640447708" geometry={nodes.group640447708.geometry} material={materials.mat23} />
      <mesh name="group93528968" geometry={nodes.group93528968.geometry} material={materials.mat23} />
      <mesh name="group26582017" geometry={nodes.group26582017.geometry} material={materials.mat23} />
      <mesh name="group1582685801" geometry={nodes.group1582685801.geometry} material={materials.mat23} />
      <mesh name="group233785688" geometry={nodes.group233785688.geometry} material={materials.mat20} />
      <mesh name="group535361081" geometry={nodes.group535361081.geometry} material={materials.mat20} />
      <mesh name="group207786523" geometry={nodes.group207786523.geometry} material={materials.mat20} />
      <mesh name="group528447376" geometry={nodes.group528447376.geometry} material={materials.mat20} />
      <mesh name="group1516688743" geometry={nodes.group1516688743.geometry} material={materials.mat20} />
      <mesh name="group1172600554" geometry={nodes.group1172600554.geometry} material={materials.mat22} />
      <mesh name="group1931015399" geometry={nodes.group1931015399.geometry} material={materials.mat24} />
      <mesh name="group938183579" geometry={nodes.group938183579.geometry} material={materials.mat24} />
      <mesh name="group1349309159" geometry={nodes.group1349309159.geometry} material={materials.mat16} />
      <mesh name="group1674386045" geometry={nodes.group1674386045.geometry} material={materials.mat21} />
      <mesh name="group1357428381" geometry={nodes.group1357428381.geometry} material={materials.mat22} />
      <mesh name="group860642019" geometry={nodes.group860642019.geometry} material={materials.mat23} />
      <mesh name="group95791140" geometry={nodes.group95791140.geometry} material={materials.mat23} />
      <mesh name="group1081262426" geometry={nodes.group1081262426.geometry} material={materials.mat19} />
      <mesh name="group1287934658" geometry={nodes.group1287934658.geometry} material={materials.mat21} />
      <mesh name="group1218717193" geometry={nodes.group1218717193.geometry} material={materials.mat21} />
      <mesh name="group1980010167" geometry={nodes.group1980010167.geometry} material={materials.mat23} />
      <mesh name="group4898611" geometry={nodes.group4898611.geometry} material={materials.mat18} />
      <mesh name="group1164661945" geometry={nodes.group1164661945.geometry} material={materials.mat23} />
      <mesh name="group410240839" geometry={nodes.group410240839.geometry} material={materials.mat11} />
      <mesh name="group446381025" geometry={nodes.group446381025.geometry} material={materials.mat23} />
      <mesh name="group242060174" geometry={nodes.group242060174.geometry} material={materials.mat15} />
      <mesh name="group1142374827" geometry={nodes.group1142374827.geometry} material={materials.mat15} />
      <mesh name="group871706007" geometry={nodes.group871706007.geometry} material={materials.mat23} />
      <mesh name="group1093773099" geometry={nodes.group1093773099.geometry} material={materials.mat23} />
      <mesh name="group1805364148" geometry={nodes.group1805364148.geometry} material={materials.mat8} />
      <mesh name="group1607230787" geometry={nodes.group1607230787.geometry} material={materials.mat16} />
      <mesh name="group977220737" geometry={nodes.group977220737.geometry} material={materials.mat16} />
      <mesh name="group1478190301" geometry={nodes.group1478190301.geometry} material={materials.mat16} />
      <mesh name="group1927025453" geometry={nodes.group1927025453.geometry} material={materials.mat16} />
      <mesh name="group2101546053" geometry={nodes.group2101546053.geometry} material={materials.mat16} />
      <mesh name="group893657134" geometry={nodes.group893657134.geometry} material={materials.mat21} />
      <mesh name="group59110847" geometry={nodes.group59110847.geometry} material={materials.mat25} />
    </group>
  )
}

useGLTF.preload('/study-table.glb')
